# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AyarlarForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AyarlarForm(object):
    def setupUi(self, AyarlarForm):
        AyarlarForm.setObjectName("AyarlarForm")
        AyarlarForm.resize(400, 500)
        AyarlarForm.setMaximumSize(QtCore.QSize(400, 500))

        self.retranslateUi(AyarlarForm)
        QtCore.QMetaObject.connectSlotsByName(AyarlarForm)

    def retranslateUi(self, AyarlarForm):
        _translate = QtCore.QCoreApplication.translate
        AyarlarForm.setWindowTitle(_translate("AyarlarForm", "Ayarlar"))
