# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HakkımdaForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HakkimdaForm(object):
    def setupUi(self, HakkimdaForm):
        HakkimdaForm.setObjectName("HakkimdaForm")
        HakkimdaForm.resize(400, 200)
        HakkimdaForm.setMaximumSize(QtCore.QSize(400, 200))

        self.retranslateUi(HakkimdaForm)
        QtCore.QMetaObject.connectSlotsByName(HakkimdaForm)

    def retranslateUi(self, HakkimdaForm):
        _translate = QtCore.QCoreApplication.translate
        HakkimdaForm.setWindowTitle(_translate("HakkimdaForm", "Hakkımda"))
