# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IletisimForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IletisimForm(object):
    def setupUi(self, IletisimForm):
        IletisimForm.setObjectName("IletisimForm")
        IletisimForm.resize(450, 360)
        IletisimForm.setMinimumSize(QtCore.QSize(450, 360))
        IletisimForm.setMaximumSize(QtCore.QSize(450, 360))
        font = QtGui.QFont()
        font.setPointSize(12)
        IletisimForm.setFont(font)
        self.formLayoutWidget = QtWidgets.QWidget(IletisimForm)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 421, 341))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.textEdit = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.textEdit)
        self.pushButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.pushButton_2)

        self.retranslateUi(IletisimForm)
        QtCore.QMetaObject.connectSlotsByName(IletisimForm)

    def retranslateUi(self, IletisimForm):
        _translate = QtCore.QCoreApplication.translate
        IletisimForm.setWindowTitle(_translate("IletisimForm", "İletişim"))
        self.label.setText(_translate("IletisimForm", "Adınız Soyadınız"))
        self.label_2.setText(_translate("IletisimForm", "E-Posta"))
        self.label_3.setText(_translate("IletisimForm", "Konu"))
        self.label_4.setText(_translate("IletisimForm", "Mesaj"))
        self.pushButton.setText(_translate("IletisimForm", "Gönder"))
        self.pushButton_2.setText(_translate("IletisimForm", "Temizle"))
