# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KuponBruteForceForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KuponBruteForceForm(object):
    def setupUi(self, KuponBruteForceForm):
        KuponBruteForceForm.setObjectName("KuponBruteForceForm")
        KuponBruteForceForm.resize(426, 396)
        font = QtGui.QFont()
        font.setPointSize(12)
        KuponBruteForceForm.setFont(font)
        self.formLayoutWidget = QtWidgets.QWidget(KuponBruteForceForm)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 411, 371))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.kupon_liste = QtWidgets.QListWidget(self.formLayoutWidget)
        self.kupon_liste.setObjectName("kupon_liste")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.kupon_liste)
        self.kupon_ekle_button = QtWidgets.QPushButton(self.formLayoutWidget)
        self.kupon_ekle_button.setObjectName("kupon_ekle_button")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.kupon_ekle_button)
        self.kupon_sil_button = QtWidgets.QPushButton(self.formLayoutWidget)
        self.kupon_sil_button.setObjectName("kupon_sil_button")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.kupon_sil_button)
        self.kupon_liste_temizle_button = QtWidgets.QPushButton(self.formLayoutWidget)
        self.kupon_liste_temizle_button.setObjectName("kupon_liste_temizle_button")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.kupon_liste_temizle_button)
        self.kupon_liste_save_button = QtWidgets.QPushButton(self.formLayoutWidget)
        self.kupon_liste_save_button.setObjectName("kupon_liste_save_button")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.kupon_liste_save_button)
        self.kupon_baslat_button = QtWidgets.QPushButton(self.formLayoutWidget)
        self.kupon_baslat_button.setObjectName("kupon_baslat_button")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.kupon_baslat_button)
        self.kupon_yukle_button = QtWidgets.QPushButton(self.formLayoutWidget)
        self.kupon_yukle_button.setObjectName("kupon_yukle_button")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.kupon_yukle_button)

        self.retranslateUi(KuponBruteForceForm)
        QtCore.QMetaObject.connectSlotsByName(KuponBruteForceForm)

    def retranslateUi(self, KuponBruteForceForm):
        _translate = QtCore.QCoreApplication.translate
        KuponBruteForceForm.setWindowTitle(_translate("KuponBruteForceForm", "Kupon Brute Force"))
        self.label.setText(_translate("KuponBruteForceForm", "Kuponlar"))
        self.kupon_ekle_button.setText(_translate("KuponBruteForceForm", "Kupon Ekle"))
        self.kupon_sil_button.setText(_translate("KuponBruteForceForm", "Seçili Kuponu Sil"))
        self.kupon_liste_temizle_button.setText(_translate("KuponBruteForceForm", "Temizle"))
        self.kupon_liste_save_button.setText(_translate("KuponBruteForceForm", "Kuponları Kaydet"))
        self.kupon_baslat_button.setText(_translate("KuponBruteForceForm", "Başlat"))
        self.kupon_yukle_button.setText(_translate("KuponBruteForceForm", "Kupon Yükle (txt)"))
