# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UrunGuncelleniyorForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UrunGuncelleniyorForm(object):
    def setupUi(self, UrunGuncelleniyorForm):
        UrunGuncelleniyorForm.setObjectName("UrunGuncelleniyorForm")
        UrunGuncelleniyorForm.resize(200, 200)
        UrunGuncelleniyorForm.setMinimumSize(QtCore.QSize(200, 200))
        UrunGuncelleniyorForm.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        UrunGuncelleniyorForm.setFont(font)
        UrunGuncelleniyorForm.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.urun_guncelleniyor_label = QtWidgets.QLabel(UrunGuncelleniyorForm)
        self.urun_guncelleniyor_label.setGeometry(QtCore.QRect(6, 12, 191, 181))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.urun_guncelleniyor_label.setFont(font)
        self.urun_guncelleniyor_label.setAlignment(QtCore.Qt.AlignCenter)
        self.urun_guncelleniyor_label.setObjectName("urun_guncelleniyor_label")

        self.retranslateUi(UrunGuncelleniyorForm)
        QtCore.QMetaObject.connectSlotsByName(UrunGuncelleniyorForm)

    def retranslateUi(self, UrunGuncelleniyorForm):
        _translate = QtCore.QCoreApplication.translate
        UrunGuncelleniyorForm.setWindowTitle(_translate("UrunGuncelleniyorForm", "Ürün Güncelleniyor"))
        self.urun_guncelleniyor_label.setText(_translate("UrunGuncelleniyorForm", ". güncelleniyor"))
