# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UrunDetayForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UrunDetayForm(object):
    def setupUi(self, UrunDetayForm):
        UrunDetayForm.setObjectName("UrunDetayForm")
        UrunDetayForm.resize(450, 220)
        UrunDetayForm.setMaximumSize(QtCore.QSize(600, 400))
        font = QtGui.QFont()
        font.setPointSize(12)
        UrunDetayForm.setFont(font)
        self.formLayoutWidget = QtWidgets.QWidget(UrunDetayForm)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 431, 201))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.urun_ismi_edit = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.urun_ismi_edit.setFont(font)
        self.urun_ismi_edit.setObjectName("urun_ismi_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.urun_ismi_edit)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.urun_url_edit = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.urun_url_edit.setFont(font)
        self.urun_url_edit.setObjectName("urun_url_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.urun_url_edit)
        self.urun_fiyat_takip_cb = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.urun_fiyat_takip_cb.setObjectName("urun_fiyat_takip_cb")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.urun_fiyat_takip_cb)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.urun_stok_takip_cb = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.urun_stok_takip_cb.setObjectName("urun_stok_takip_cb")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.urun_stok_takip_cb)
        self.urun_kontrol_suresi_time = QtWidgets.QTimeEdit(self.formLayoutWidget)
        self.urun_kontrol_suresi_time.setObjectName("urun_kontrol_suresi_time")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.urun_kontrol_suresi_time)
        self.urun_kaydet_button = QtWidgets.QPushButton(self.formLayoutWidget)
        self.urun_kaydet_button.setObjectName("urun_kaydet_button")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.urun_kaydet_button)
        self.urun_sil_button = QtWidgets.QPushButton(self.formLayoutWidget)
        self.urun_sil_button.setObjectName("urun_sil_button")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.urun_sil_button)

        self.retranslateUi(UrunDetayForm)
        QtCore.QMetaObject.connectSlotsByName(UrunDetayForm)

    def retranslateUi(self, UrunDetayForm):
        _translate = QtCore.QCoreApplication.translate
        UrunDetayForm.setWindowTitle(_translate("UrunDetayForm", "Ürün Detay"))
        self.label.setText(_translate("UrunDetayForm", "Ürün ismi: "))
        self.label_2.setText(_translate("UrunDetayForm", "URL: "))
        self.urun_fiyat_takip_cb.setText(_translate("UrunDetayForm", "Fiyat Takip Et"))
        self.label_3.setText(_translate("UrunDetayForm", "Kontrol Süresi"))
        self.urun_stok_takip_cb.setText(_translate("UrunDetayForm", "Stok Takip Et"))
        self.urun_kaydet_button.setText(_translate("UrunDetayForm", "Kaydet"))
        self.urun_sil_button.setText(_translate("UrunDetayForm", "Ürün Sil"))
